### ISSUE TITLE
Pin on pydantic for v1.4.1 is too strict

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/xopt-feedstock#38]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Rather than pinning `pydantic == 1.10.9` for version 1.4.1, the pin should be `pydantic <2` to allow for newer versions of pydantic (v1.x is currently at 1.10.13).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by ChristopherMayes** [comment]
This is resolved with Xopt V2
